### ISSUE TITLE
Cant convert survey responses to data.frame

### ISSUE THREAD

**Issue by matentzn** [cloudyr/Rmonkey#5]
I was super greatful when I saw your tool.. However, I have trouble to convert the survey responses to a data frame. I can see that after calling `g <- getresponses(r, s[[2]])`, I do get the results of the survey. However, when calling `as.data.frame(g)`, I get: 

```R
Error in vector(type, length) : 
  vector: cannot make a vector of mode 'NULL'.
In addition: There were 40 warnings (use warnings() to see them)

The warnings all look like:
Warning messages:
1: In mapply(function(i, type) { ... :
  longer argument not a multiple of length of shorter
2: In mapply(function(i, type) { ... :
  longer argument not a multiple of length of shorter
3: In mapply(function(i, type) { ... :
  longer argument not a multiple of length of shorter
4: In mapply(function(i, type) { ... :
```

Could it have anything to do with 1) incomplete responses or 2) weird special characters in the questions? Cheers!

**Comment by leeper** [comment]
Can you paste in the output of `str(g)` for me? If it's long, just the first 5-10 lines would do.

**Comment by matentzn** [comment]
List of 40
 $ :List of 2
  ..$ respondent_id: chr "3975598496"
  ..$ questions    :List of 28
  .. ..$ :List of 2
  .. .. ..$ answers    :List of 1
  .. .. .. ..$ :List of 2
  .. .. .. .. ..$ text: chr "Living Semantic Platform"
  .. .. .. .. ..$ row : chr "0"
  .. .. ..$ question_id: chr "751902353"
  .. ..$ :List of 2
  .. .. ..$ answers    :List of 1
  .. .. .. ..$ :List of 1
  .. .. .. .. ..$ row: chr "8537183504"
  .. .. ..$ question_id: chr "751903785"

If you like, I also have the entire output as a text file! Thanks.

**Comment by leeper** [comment]
Hmm...that looks reasonable. After you get the error, can you type `traceback()` into the R console and copy the output from that?

**Comment by matentzn** [comment]
6: vector(type, length)
5: allocate_column(df[[var]], nrows, dfs, var)
4: output_template(dfs, nrows)
3: rbind.fill(tmp)
2: as.data.frame.sm_response_list(g)
1: as.data.frame(g)

Could it have to do something with special chars? Ore maybe with incomplete survey responses?

**Comment by leeper** [comment]
Okay, so the error is occurring in the very last part of the data.frame construction, specifically inside a call to `plyr::rbind.fill`, which is supposed to coerce a list of data.frames into a single data.frame. This should tolerate missing data and all sorts of other irregularities. Is there anything unusual about the particular survey you're working with?

**Comment by matentzn** [comment]
If you want, I can can share the survey with you (data is public anyways). Here is a link to the actual survey: https://www.surveymonkey.com/r/6F9K89X

Some things I noted going through it: 1) size: The answers are ocassionally long, ie, have long freetext sections or many checkboxes to select from. 2) chars: There are often non asci, and maybe even non utf-8 characters in the responses (if that would be permitted by survey monkey).  Also, many lists of checkboxes contain slashes, dont know whether that could be a problem. 3) Incomplete suveys. 4) Ocassionally long comments to explain the questions.

**Comment by matentzn** [comment]
(i could also send you a csv data export dump from survey monkey)

**Comment by leeper** [comment]
I've been trying to think about how to debug this. The problem is that there are actually a lot of API calls happening inside the `as.data.frame` method so it's hard for you to just send me something to examine because there are several moving pieces. If you're willing to do a bit of debugging for me, that might be the best way to figure this out.

Specifically, the object we need to look at is [this one](https://github.com/leeper/Rmonkey/blob/master/R/getresponses.r#L125) inside the `as.data.frame.sm_response_list` method. This is what is being passed to `plyr::rbind.fill` and causing the failure. If you run `debug(as.data.frame.sm_response_list)` (or `debugonce(as.data.frame.sm_response_list)`) and then try `as.data.frame(g)` again, you can then walk through the code inside the `as.data.frame` method one by and one you should be able to get to the `tmp <- ...` line, evaluate it, and then examine it. If it's anything other than a list of data.frames, it's a problem in Rmonkey. If it's a list of data.frames, then the problem is in plyr. Either way, I'd like to know. Can you give that a try and report back what `tmp` looks like?

**Comment by matentzn** [comment]
"lot of API calls happening inside the as.data.frame" --> you mean API calls to survey monkey? If that is so, then the problem might lie in the insufficiency of my developer plan I am subscribed to.. 

Thanks a lot for your help. I wont be able to do this today, as I am on a trip right now until next Monday.. I will try to do it then. I will let you know what I find out, and thanks again!

**Comment by leeper** [comment]
Well, ideally not "a lot" if I coded it all correctly, but definitely some. That's because the API doesn't really return survey responses - it returns codes that have API-specific meanings that can be translated to survey responses by referencing them against a description of the survey structure, so it requires some back and forth. I don't think exceeding your plan is the issue here but it's possible. If that is the case, I can probably modify the package to behave better. Let me know when you get a chance to look into it more.

**Comment by bcaessens** [comment]
Hi,
First off, thank you for putting this together, it is (potentially :-) a time saver. 
I am not sure if this is the same issue, but anyway. When I run the as.data.frame on a response object, the dataframe is full of numbers. Like so:

g=getresponses(r[[1]],s[[1]])
> g
[[1]]
Responent ID: 4189125149 

attr(,"class")
[1] "sm_response_list"

This looks okay from what I have been reading, also, str(g) gives me what I expect. But, next
> as.data.frame(g)
returns 
  848725401.1 848725401.2 848727192.1 848727192.2 848727192.3 848727192.4 848727192.5 848727192.6
1  9383702101  9383702100  9383715805  9383715806  9383715802  9383715809  9383715810  9383715802
  848727192.7 848727192.8 848727192.9 848727192.10 848727192.11 848727192.12 848727192.13
1  9383715805  9383715806  9383715803   9383715809   9383715810   9383715803   9383715805
  848727192.14 848727192.15 848727192.16 848727192.17 848727192.18
1   9383715806   9383715804   9383715809   9383715812   9383715804

I have reinstalled from github, I have tried some of the things in here. But nothing so far. 
Any idea what is missing or how I can find out? 

Thanks a lot.
Bernie

**Comment by leeper** [comment]
Can you try just `as.data.frame(g[[1]])`? And, maybe also try `as.data.frame(g, details = surveydetails(s[[1]]$survey_id))`? What do those do for you?

Also, what kind of response structure are you expecting for this survey exactly?

**Comment by bcaessens** [comment]
Hi Thomas,

Appreciate your reply. I tried both of them, but none seem to give me something intelligible in the survey, so I keep getting the answer id numbers, and not the actual text or response. 

As to the expected response structure, my guess (based on using excel/csv exports from surveymonkey before) would be to get the question label in the df columns, respondents answers in the rows. In this case, I used a simple test survey with a title, and just two questions (matrix-style). 

Looking at the code of the as.data.frame.sm_response I understand that you have all of the 'mapping' info from surveydetails(). When I run str(surveydetails(s[[1]]) I do see all of the information there. But, somehow, it is not being used to look-up the actual responses. Any clues as to how I can find out what's going on. I will try stepping through the code line by line. 

Kind regards,
Bernie

**Comment by bcaessens** [comment]
Hi Thomas,

I extracted the code for as.data.frame from getresponses.R and ran it with through debug. Not quite sure it this is of any help, but here is what I found. Here is the output on error:
debug at #33: responses <- mapply(function(i, type) {
    if (type %in% c("single_choice", "multiple_choice")) 
        unname(answerchoices[match(unlist(i$answers), names(answerchoices))])
    else unname(unlist(i$answers))
}, x$questions, qtypes)
Browse[2]> n
Error in mapply(function(i, type) { : 
  zero-length inputs cannot be mixed with those of non-zero length

One of the questions is a matrix with drop-down boxes. Could this be the problem? 
Hope this shines more light for you than me ;-)
Bernie.

**Comment by leeper** [comment]
@bcaessens  Yes, that looks helpful because it appears the function does not accommodate the type of question you're asking. I'll try to create an example survey and work through it. I'm a bit swamped with other things at the moment, so I can't promise anything for the next few days.

**Comment by BenjaminWatts** [comment]
hey - i think I have a similar problem - any suggestions for how I could get around or contribute a solution would be much appreciated

**Comment by leeper** [comment]
I believe I have fixed this. Can you check whether the latest version is now working for you, @BenjaminWatts @matentzn @bcaessens ?

**Comment by mstevens11** [comment]
Hello leeper,
I am having the same problem.  I just reinstalled plyr and the problem is still there unfortunately.  Thanks for any assistance on this!
Megan

**Comment by mstevens11** [comment]
Excuse me - I hadn't read the previous thread closely.  I am not using survey data, but I was having the same problem with the rbind.fill function of plyr.  For future reference, the problem was because some of the column names in the data frame were NA.  I renamed the column names and the problem was solved.  Hope this will help someone in the future!
